package GUI;


import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jaider
 */
public class a extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    private int xMouse, yMouse;

    public a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreApp = new javax.swing.JLabel();
        sloganApp = new javax.swing.JLabel();
        separadorIcono = new javax.swing.JSeparator();
        iconoDer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        iniciarTitulo = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        separadorNombre = new javax.swing.JSeparator();
        idLabel = new javax.swing.JLabel();
        reunionBoton = new javax.swing.JPanel();
        reunionLabel = new javax.swing.JLabel();
        separadorNombre1 = new javax.swing.JSeparator();
        direccionLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        separadorNombre2 = new javax.swing.JSeparator();
        idTextField = new javax.swing.JTextField();
        imagenBoton = new javax.swing.JPanel();
        cambiarLabel = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JPanel();
        cerrarBoton = new javax.swing.JPanel();
        cerrarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        nombreApp.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        nombreApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreApp.setText("me.Chat");

        sloganApp.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        sloganApp.setText("Conecta.Comunica.Comparte");

        iconoDer.setBackground(new java.awt.Color(255, 255, 255));
        iconoDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separadorIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sloganApp)
                    .addComponent(nombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(iconoDer, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(nombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(sloganApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoDer, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 390, 610));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 30));

        iniciarTitulo.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        iniciarTitulo.setText("Iniciar");
        jPanel2.add(iniciarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        imagenLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        imagenLabel.setText("Foto de Perfil");
        jPanel2.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        direccionTextField.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        direccionTextField.setForeground(new java.awt.Color(204, 204, 204));
        direccionTextField.setText("localhost...");
        direccionTextField.setBorder(null);
        direccionTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                direccionTextFieldMousePressed(evt);
            }
        });
        jPanel2.add(direccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 230, -1));
        jPanel2.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 220, 10));

        idLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        idLabel.setText("ID de la Reunión");
        jPanel2.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        reunionBoton.setBackground(new java.awt.Color(204, 204, 255));
        reunionBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reunionBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reunionBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reunionBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reunionBotonMouseExited(evt);
            }
        });

        reunionLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        reunionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reunionLabel.setText("Iniciar Reunión");

        javax.swing.GroupLayout reunionBotonLayout = new javax.swing.GroupLayout(reunionBoton);
        reunionBoton.setLayout(reunionBotonLayout);
        reunionBotonLayout.setHorizontalGroup(
            reunionBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reunionBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reunionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        reunionBotonLayout.setVerticalGroup(
            reunionBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reunionBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reunionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(reunionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 210, 40));
        jPanel2.add(separadorNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, 10));

        direccionLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        direccionLabel.setText("Dirección IP");
        jPanel2.add(direccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        nombreTextField.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        nombreTextField.setForeground(new java.awt.Color(204, 204, 204));
        nombreTextField.setText("Mi nombre...");
        nombreTextField.setBorder(null);
        nombreTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreTextFieldMousePressed(evt);
            }
        });
        jPanel2.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, -1));

        nombreLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        nombreLabel.setText("Nombre");
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel2.add(separadorNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, 10));

        idTextField.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        idTextField.setForeground(new java.awt.Color(204, 204, 204));
        idTextField.setText("1234...");
        idTextField.setBorder(null);
        idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idTextFieldMousePressed(evt);
            }
        });
        jPanel2.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, -1));

        imagenBoton.setBackground(new java.awt.Color(204, 204, 255));
        imagenBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagenBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagenBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagenBotonMouseExited(evt);
            }
        });

        cambiarLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cambiarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiarLabel.setText("Seleccionar\n\n");

        javax.swing.GroupLayout imagenBotonLayout = new javax.swing.GroupLayout(imagenBoton);
        imagenBoton.setLayout(imagenBotonLayout);
        imagenBotonLayout.setHorizontalGroup(
            imagenBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagenBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cambiarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        imagenBotonLayout.setVerticalGroup(
            imagenBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(imagenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 210, 40));

        barraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        barraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraSuperiorMouseDragged(evt);
            }
        });
        barraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraSuperiorMousePressed(evt);
            }
        });

        cerrarBoton.setBackground(new java.awt.Color(255, 255, 255));
        cerrarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarBotonMouseExited(evt);
            }
        });

        cerrarLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cerrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarLabel.setText("X");

        javax.swing.GroupLayout cerrarBotonLayout = new javax.swing.GroupLayout(cerrarBoton);
        cerrarBoton.setLayout(cerrarBotonLayout);
        cerrarBotonLayout.setHorizontalGroup(
            cerrarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        cerrarBotonLayout.setVerticalGroup(
            cerrarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cerrarBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cerrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addComponent(cerrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cerrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraSuperiorMousePressed


    private void barraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraSuperiorMouseDragged


    private void cerrarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBotonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarBotonMouseClicked


    private void cerrarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBotonMouseEntered
        cerrarBoton.setBackground(Color.RED);
        cerrarLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_cerrarBotonMouseEntered


    private void cerrarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBotonMouseExited
        cerrarBoton.setBackground(Color.WHITE);
        cerrarLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarBotonMouseExited


    private void imagenBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imagenBotonMouseClicked


    private void imagenBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenBotonMouseEntered
        imagenBoton.setBackground(new Color(134, 134, 255));
    }//GEN-LAST:event_imagenBotonMouseEntered


    private void imagenBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenBotonMouseExited
        imagenBoton.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_imagenBotonMouseExited


    private void reunionBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reunionBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reunionBotonMouseClicked


    private void reunionBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reunionBotonMouseEntered
        reunionBoton.setBackground(new Color(134, 134, 255));
    }//GEN-LAST:event_reunionBotonMouseEntered


    private void reunionBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reunionBotonMouseExited
        reunionBoton.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_reunionBotonMouseExited


    private void nombreTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextFieldMousePressed
        if (nombreTextField.getText().equals("Mi nombre...")) {
            nombreTextField.setText("");
            nombreTextField.setForeground(Color.BLACK);
        }

        if (idTextField.getText().isEmpty()) {
            idTextField.setText("1234...");
            idTextField.setForeground(Color.GRAY);
        }

        if (direccionTextField.getText().isEmpty()) {
            direccionTextField.setText("localhost...");
            direccionTextField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreTextFieldMousePressed


    private void idTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTextFieldMousePressed
        if (idTextField.getText().equals("1234...")) {
            idTextField.setText("");
            idTextField.setForeground(Color.BLACK);
        }

        if (nombreTextField.getText().isEmpty()) {
            nombreTextField.setText("Mi nombre...");
            nombreTextField.setForeground(Color.GRAY);
        }

        if (direccionTextField.getText().isEmpty()) {
            direccionTextField.setText("localhost...");
            direccionTextField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_idTextFieldMousePressed

    private void direccionTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionTextFieldMousePressed
        if (direccionTextField.getText().equals("localhost...")) {
            direccionTextField.setText("");
            direccionTextField.setForeground(Color.BLACK);
        }

        if (nombreTextField.getText().isEmpty()) {
            nombreTextField.setText("Mi nombre...");
            nombreTextField.setForeground(Color.GRAY);
        }

        if (idTextField.getText().isEmpty()) {
            idTextField.setText("1234...");
            idTextField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_direccionTextFieldMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a().setVisible(true);
            }
        });
    }

    private void pintarImagenes(JLabel jlabel, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage()
                .getScaledInstance(jlabel.getWidth(),
                        jlabel.getHeight(), Image.SCALE_DEFAULT));
        jlabel.setIcon(icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel cambiarLabel;
    private javax.swing.JPanel cerrarBoton;
    private javax.swing.JLabel cerrarLabel;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel iconoDer;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel imagenBoton;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel iniciarTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreApp;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel reunionBoton;
    private javax.swing.JLabel reunionLabel;
    private javax.swing.JSeparator separadorIcono;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorNombre1;
    private javax.swing.JSeparator separadorNombre2;
    private javax.swing.JLabel sloganApp;
    // End of variables declaration//GEN-END:variables
}
